### ISSUE TITLE
why is VAST is xsd:sequence rather than xsd:all?

### ISSUE THREAD

**Issue by jimdigriz** [InteractiveAdvertisingBureau/vast#21]
Can someone explain why the XSD's use `xsd:sequence` rather than `xsd:all` and so enforce the ordering of the elements?  I cannot think of a technical reason (alphabetical means the reasoning is not for SAX and optimising reading in for RTB) so it would be helpful to know why this constraint is present?

#9 hints that it is desirable (though I cannot see anything in the [VAST 4.1 spec](https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf) stating alphabetical ordering is required) but I cannot see anywhere why.  `grep`'ing the project also shows nothing but a statement in the release notes that this will be done but lacks the 'why'.

As I cannot find any explaination was this just a cosmetic reason?  If so it needlessly makes creating VAST documents trickier and definately something that can trip up newcomers to VAST and is something I think most (including myself) find unexpected.

Looking forward to hearding the why, maybe it could be made into an IAB pub quiz question!

**Comment by goosemanjack** [comment]
The xsd:all element enforces a cardinality of zero or one only. If you cross reference the xsd CreativeResource_type (around line 214) against the VAST 4.1 spec, section 3.15, you can see that all the sub elements (StaticResource, HTMLResource, IFrameResource) can be zero to unbounded. As such, the xsd:all element would result in valid VAST xml being rejected should multiple sub-elements of the given type be included.

While these elements are not supposed to be subject to any ordering restrictions per the spec, we are constrained by the shortcomings of XSD format and schema validation itself. A design trade-off had to be made. The choice of using xsd:sequence means that the VAST can be adjusted to validate, whereas xsd:all would result in some valid VAST tags never passing validation, regardless of adjustments to the VAST.

**Comment by goosemanjack** [comment]
I understand and share your frustration. You are not alone in your frustration with XML/XSD as [this thread on StackOverflow](https://stackoverflow.com/questions/3325247/xml-validation-with-xsd-how-to-avoid-caring-about-the-sequence-of-the-elements) shows. These limitations are also some of many reasons why most industries have moved off of XML and onto JSON, ProtoBuff, etc. You should also consider that the last major update to XSD happened in 2012 and to my knowledge there is no current work on this spec when making your design decisions.

In terms of official guidance, I can only repeat what I've stated previously in this thread. Namely, the recommended way to use the XSD is to generate a class structure in your preferred programming language, then deserialize the incoming VAST XML into this structure. 

Setting the sequence issues aside, XSD is a very limiting language and is only able to represent a subset of the business rules around VAST documents. The XSD should be considered an intermediary format and not a final validator. It is up to implementors to build a validator and check the business rules within the spec as they see fit.

**Comment by jimdigriz** [comment]
Okay, but this is not addressing that people are using your XSDs to 
validate *other* people's tags.

Why not create two sets of XSDs, one in a directory called 'for validation 
use' and the other named appropriately for your use case?

You need to try to make it hard for people to do the wrong thing, and easy 
to do the right thing.

Just repeating 'XSD does not let me do what I wanted' ignores the problem 
of people actively mis-using your work.

**Comment by gilliginsisland** [comment]
In XSD 1.0, the children of xs:all must have maxOccurs set to 1.
In XSD 1.1 this constraint is lifted.

Why not just use <xs:all> and require xsd 1.1 parsers to be used?
