### ISSUE TITLE
Is it valid to have a creative element within a wrapper element in vast3 and vast4 spec?

### ISSUE THREAD

**Issue by Doca** [InteractiveAdvertisingBureau/vast#39]
A customer set up a campaign (declared as vast4) with a creative (linear) and also Mediafiles inside of a vast wrapper having also a VASTAdTagURI redirecting to another xml which also has linear creatives. 
We have a discussion and I want to make sure I got the specs right.[https://github.com/InteractiveAdvertisingBureau/vast/blob/f28dbb4768744062fcb638a1859364cdafb3a449/vast_4.2.xsd#L21](https://github.com/InteractiveAdvertisingBureau/vast/blob/f28dbb4768744062fcb638a1859364cdafb3a449/vast_4.2.xsd#L21)[https://github.com/InteractiveAdvertisingBureau/vast/blob/f28dbb4768744062fcb638a1859364cdafb3a449/vast3_draft.xsd#L279](https://github.com/InteractiveAdvertisingBureau/vast/blob/f28dbb4768744062fcb638a1859364cdafb3a449/vast3_draft.xsd#L279)
I see creative elements inside of the wrapper element in the specification of vast3 but not in vast4. But I have a lack of fantasy what a player should do with two linear creative elements (one from the wrapper and one from the redirect). My question: Are creatives valid inside of a wrapper? In the case of VAST3 what could be the intended behavior of the player?

**Comment by fkoch-sc** [comment]
A creative node is allowed and would carry additional trackers from the ad system serving the wrapper ad, but media files are not allowed, those need to be part of an inline ad. The player is supposed to request the URL provided inside VASTAdTagURI node to receive an inline or another wrapper ad.
