### ISSUE TITLE
Incorrect restriction in TrackingEvents_type in vast_4.0.xsd

### ISSUE THREAD

**Issue by Alexuy** [InteractiveAdvertisingBureau/vast#5]
In <xs:restriction base="xs:token"> tag missing next tracking events:

- timeSpentViewing
- minimize
- overlayViewDuration
- otherAdInteraction
- acceptInvitationLinear

Must be renamed:

- expand to adExpand
- collapse to adCollapse
- fullscreen to playerExpand
- exitFullscreen to playerCollapse

**Comment by goosemanjack** [comment]
Updated tracking event tokens to match spec April 2016
