### ISSUE TITLE
Corrections for VAST4.xsd

### ISSUE THREAD

**Issue by Alexuy** [InteractiveAdvertisingBureau/vast#6]
From VAST 4.0 documentation:

1. Section 3.10.1: ClickThrough bounded 0-1 (if <VideoClicks> is used), but now VideoClicks_InlineChild_type can has collection of ClickThrough elements

2. Section 3.7.3: CreativeExtension element: new attribute 'type' -  The MIME type of any code that might be included in the extension.

3. Section 3.15.3: HTMLResource element: HTMLResourceType now haven't attribute "xmlEncoded", that must be only String with CDATA.

4. Section 3.4.1: AdSystem element: must be required in response, if its parent is 'InLine' element

5. Section 3.4.4: Category element: bounded 0+, but now we can set only one category

6. Section 3.7.1: UniversalAdId element: attributes idRegistry and idValue must be required

7. Section 3.9.2: Mezzanine element: can be simplified to CDATA-string element (now it is complexType), because it hasn't any attributes

8. Section 3.9.1: MediaFile element: attribute 'adaptiveStreaming' must be removed

9. Section 3.11: Icons element: now it can be in Wrapper element too, but now we have it only in Linear element.

10. Section 3.11.1: Icon element: attributes 'program', 'width', 'height', 'xPosition', 'yPosition' must be not required.

11. Sections 3.11.4 and 3.11.5: IconClickThrough and IconClickTracking elements now are confused: IconClickThrough must have only String body with CDATA and IconClickTracking can have attribute 'id'

12. Section 3.11.2: IconViewTracking element can't have attribute 'id', it is only URI string with CDATA. IconTrackingUri_type is redudant

13. Section 3.13.4: CompanionClickTracking element: must have 'id' attribute, but now it is simple String

14. Section 3.19.1: VASTAdTagURI element: can be simplified to String with CDATA, now it is complex type

15. Section 3.19: Wrapper element: sub-elemnt 'Creatives' is not required

16. Please, rename 'Verification_type' to 'VerificationWrapper_type'

**Comment by goosemanjack** [comment]
Fixes currently checked in to development branch

Item 1 - 3.10.1 - Fixed
Item 2 - 3.7.3 - Added attribute explicitly
Item 3 - 3.15.3 - Removed incorrect attribute and added comment from spec
Item 4 - 3.4.1 - Changed AdSystem to be bounded at 1 (required)
Item 5 - 3.4.4 - Multiple Category elements allowed
Item 6 - 3.7.1 - Attributes on UniversalAdId changed to required

**Comment by goosemanjack** [comment]
Item 7 - 3.9.2 - No change required
Item 8 - 3.9.1 - Removed adaptive streaming
Item 9 - 3.11 - Icons element is defined in Linear_Base_type, which is inherited from by both Wrapper/Linear and Inline/Linear, so no change
Item 10 - 3.11.1 - All Icon attributes now optional

**Comment by goosemanjack** [comment]
Item 11 - 3.11.4 and 3.11.5  Adjusted to fix attributes.
Item 12 - 3.11.2 - Fixed IconViewTracking  to only have simple uri
Item 13 -  3.13.4 - Modified to add id as required attribute to CompanionClickTracking
Item 14 -  3.19.1 - Simplified VASTAdTagURI element
Item 15 - 3.19 - Creatives under Wrapper no longer required
Item 16 - Renamed Verification_type' to 'VerificationWrapper_type'

All changes applied in xsd version 4.0.5
