### ISSUE TITLE
Attributes in UniversalAdId are not marked as required

### ISSUE THREAD

**Issue by goosemanjack** [InteractiveAdvertisingBureau/vast#7]
UniveralAdId is missing Attribute use=required.

Reported via Mayank

**Comment by goosemanjack** [comment]
Invalid bug report.
The UniversalAdId is required by virtue of minOccurs=1 maxOccurs=1
The attribute use=required only applies to attributes.

**Comment by amitshetty** [comment]
The title was incorrect while the description was correct. Both the attributes (idRegistry and idValue) are required per the spec.
Thanks!

**Comment by goosemanjack** [comment]
Both attributes marked as required.
