### ISSUE TITLE
VAST 3.0 Creatives required under Wrapper 

### ISSUE THREAD

**Issue by dbemiller** [InteractiveAdvertisingBureau/vast#8]
The [VAST 3.0 schema](https://github.com/InteractiveAdvertisingBureau/vast/blob/master/vast3_draft.xsd) considers the following XML to be valid:

```xml
<VAST version="3.0">
    <Ad>
        <Wrapper>
            <AdSystem>prebid.org vastUrl redirect wrapper</AdSystem>
            <VASTAdTagURI>http://www.google.com</VASTAdTagURI>
            <Impression>www.my-tracking.url.com</Impression>
            <Creatives></Creatives>
        </Wrapper>
    </Ad>
</VAST>
```

It also considers the following XML to be invalid:

```xml
<VAST version="3.0">
    <Ad>
        <Wrapper>
            <AdSystem>prebid.org vastUrl redirect wrapper</AdSystem>
            <VASTAdTagURI>http://www.google.com</VASTAdTagURI>
            <Impression>www.my-tracking-url.com</Impression>
        </Wrapper>
    </Ad>
</VAST>
```

The only difference is the empty "Creatives" tag.

In section 2.4.11, [the PDF spec](https://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf) says:

> Three optional elements are also available:
>
> - \<Creatives\>: Contains a creative element, which describe the Wrapper Ad creative

Given this, I would expect the opposite behavior. It seems like XML with *no* `Creatives` tag should be valid, but XML with an *empty* `Creatives` tag should be invalid. (XML with a `Creatives` tag containing a single element should also be valid).

**Comment by mgriego** [comment]
Look at section 2.4.1.3:  ```If the <Creatives> element is included    in    the    Wrapper,    
one    or    more    
<Creative>
elements    may    be    included    (but    is    not    required;    an    empty    
<Creatives>
element    is
acceptable).    A
