### ISSUE TITLE
Inline order of elements does not respect IAB latest specs

### ISSUE THREAD

**Issue by brunonieuwenhuys** [InteractiveAdvertisingBureau/vast#9]
Looks like the order of the inline element does not follow the IAB latest specs.

I have the following sequence
<Ad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="AdswizzAd14783">
<InLine>
<AdSystem>Adswizz</AdSystem>
<AdTitle>
<![CDATA[ Dunkin Donuts Audio ]]>
</AdTitle>
<Impression id="14783">...</Impression>
<Category authority="http://www.iabtechlab.com/categoryauthority">IAB24</Category>
<Description>...</Description>
<Advertiser>www.dunkindonuts.com</Advertiser>
<Extensions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">...</Extensions>
<Creatives>...</Creatives>
</InLine>
</Ad>

And I get the following error when validating against the xsd
Not valid.
Error - Line 5, 10: org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 10; cvc-complex-type.2.4.a: Invalid content was found starting with element 'AdTitle'. One of '{"http://www.iab.com/VAST":Error, "http://www.iab.com/VAST":Extensions, "http://www.iab.com/VAST":Impression}' is expected.

**Comment by goosemanjack** [comment]
XSD is very limiting in terms of how we can respect ordering of elements. Elements are in alphabetical order with respect to both their inherited type, then their specific type. It is a limitation of XSD that we cannot fully honor alphabetical order when using inherited types. My suggestion is to generate code elements from the XSD and programmatically test your VAST, as this is the most common usage of the XSD.

**Comment by jimdigriz** [comment]
My question is why does the ordering matter?

**Comment by goosemanjack** [comment]
The ordering does not matter per spec. This is a failure in the design of XSD schema validation and language and is beyond our control. The language is not rich enough to express our intent accurately.
